export const MESSAGES = {
    SERVER_ERROR: 'Internal Server Error',
    NOT_AFFECTED: 'Not affected',
    INVALID_PARAMETERS: 'Invalid Parameters',
    NOT_AUTHORIZE: 'Not Authorized for this action',
    ID_REQUIRED: 'Id Required',
    UPDATE_APP: 'Please Update your Application',
    GOALS_LIST: 'Goals List getting successfully',
    EMAIL_SEND: 'Email sent Successfully',
    IMAGE_FILE: 'Invalid file format. Only JPG, JPEG, SVG and PNG are allowed',
    USER: {
        EMAIL_NOT_FOUND: 'Email not found',
        REACTIVATE_ACCOUNT: 'Reactivate your Account',
        ACCOUNT_REACTIVATED: 'Your Account is re-activated',
        EMAIL_EXISTS: 'Email Already Exists',
        USER_EXISTS: 'User already exists with this Email',
        GET_ALL_USERS: 'User fetched successfully',
        CREATE_SUCCESS: 'User created successfully',
        NOT_FOUND: 'User not found',
        GET_USER: 'User Getting Successfully',
        UPDATE_FAILED: 'User update process failed',
        UPDATE_SUCCESS: 'User Update Successfully',
        LIST_NOT_FOUND: 'User list not found',
        LIST_FETCH: 'User list fetched',
        SIGN_UP_NOT_VALID: 'User data not valid',
        SIGN_UP_FAILED: 'User sign up failed',
        DELETE_USER: 'User Delete Successfully',
        PASSWORD_CHANGE_STRING: 'Password change String sent Successfully',
        PASSWORD_CHANGE_STRING_WRONG: 'Password change String is null or wrong',
        CHANGE_PASSWORD: 'Password change Successfully',
        PASSWORD_TOKEN_SENT: 'Password reset token sent successfully',
        PASSWORD_NOT_MATCH: 'newPassword and confirmPassword does not match',
        OLD_PASSWORD_INVALID: 'old password is invalid',
        VERIFY_OTP: 'Otp Verify Successfully',
        INVALID_OTP: 'Otp is Invalid or expired',
        INVALID_OTP_STRING: 'Otp String is Invalid',
        SESSION_EXPIRES: 'session expired or user not found',
        USER_SESSION_TIME: 'Total Time of all sessions successfully getting',
        USER_LONGEST_SESSION: 'User Longest Session getting Successfully',
        USER_LONGEST_SESSION_NOT_FOUND: 'User did not start any session till now',
        USER_SESSION_TIME_BY_DAY: 'User data getting successfully',
    },
    SUB_CATEGORY: {
        SUB_CATEGORY_EXISTS: 'Sub Category already exists',
        GET_ALL_SUB_CATEGORY: 'Sub Category fetched successfully',
        CREATE_SUCCESS: 'Sub Category created successfully',
        NOT_FOUND: 'Sub Category not found',
        GET_SUB_CATEGORY: 'Sub Category Getting Successfully',
        UPDATE_FAILED: 'Sub Category update process failed',
        UPDATE_SUCCESS: 'Sub Category Update Successfully',
        DELETE_SUB_CATEGORY: 'Sub Category Delete Successfully',
    },
    SESSION: {
        SESSION_EXISTS: 'Session already exists',
        GET_ALL_SESSION: 'Session fetched successfully',
        CREATE_SUCCESS: 'Session created successfully',
        NOT_FOUND: 'Session not found',
        GET_SESSION: 'Session Getting Successfully',
        UPDATE_FAILED: 'Session update process failed',
        UPDATE_SUCCESS: 'Session Update Successfully',
        DELETE_SESSION: 'Session Delete Successfully',
        WRONG_DURATION: 'Wrong Duration',
        START_SESSION: 'Session Start',
        STOP_SESSION: 'Session Stop',
        NOT_START: 'please session start first',
        LONGEST_SESSION: 'Longest sessions Getting Successfully',
    },
    PREFERENCES: {
        PREFERENCES_EXISTS: 'Preferences already exists',
        GET_ALL_PREFERENCES: 'Preferences fetched successfully',
        CREATE_SUCCESS: 'Preferences created successfully',
        NOT_FOUND: 'Preferences not found',
        GET_PREFERENCES: 'Preferences Getting Successfully',
        UPDATE_FAILED: 'Preferences update process failed',
        UPDATE_SUCCESS: 'Preferences Update Successfully',
        DELETE_PREFERENCES: 'Preferences Delete Successfully',
    },
    ACHIEVEMENTS: {
        ACHIEVEMENTS_EXISTS: 'Achievements already exists',
        GET_ALL_ACHIEVEMENTS: 'Achievements fetched successfully',
        CREATE_SUCCESS: 'Achievements created successfully',
        NOT_FOUND: 'Achievements not found',
        GET_ACHIEVEMENTS: 'Achievements Getting Successfully',
        UPDATE_FAILED: 'Achievements update process failed',
        UPDATE_SUCCESS: 'Achievements Update Successfully',
        DELETE_ACHIEVEMENTS: 'Achievements Delete Successfully',
        USER_GOT: 'User Got this Achievement',
        USER_ALREADY_GOT: 'User Already got this Achievement'
    },
    NOTIFICATION: {
        NOTIFICATION_EXISTS: 'Notifications already exists',
        GET_ALL_NOTIFICATION: 'Notifications fetched successfully',
        CREATE_SUCCESS: 'Notifications created successfully',
        NOTIFICATION_SENT: 'Notification sent successfully',
        NOT_FOUND: 'Notifications not found',
        GET_NOTIFICATION: 'Notification getting Successfully',
        UPDATE_FAILED: 'Notifications update process failed',
        UPDATE_SUCCESS: 'Notifications Update Successfully',
        DELETE_NOTIFICATION: 'Notifications Delete Successfully',
        NOT_SEND: 'Notification not Send',
        DEVICE_TOKEN_NOT_FOUND: 'Device Token not Found',
    },
    CATEGORY: {
        CATEGORY_EXISTS: 'Category already exists',
        GET_ALL_CATEGORY: 'Category fetched successfully',
        CREATE_SUCCESS: 'Category created successfully',
        NOT_FOUND: 'Category not found',
        GET_CATEGORY: 'Category Getting Successfully',
        UPDATE_FAILED: 'Category update process failed',
        UPDATE_SUCCESS: 'Category Update Successfully',
        DELETE_CATEGORY: 'Category Delete Successfully',
    },
    AUTH: {
        LOGIN_SUCCESS: 'User LoggedIn Successfully',
        INVALID_PASSWORD: 'Password is invalid',
        REQUIRED: 'User Login Required',
        INVALID_EMAIL: 'Email is Invalid',
    },

    PRIVACY_POLICY: {
        PRIVACY_POLICY_EXISTS: 'Privacy Policy already exists',
        GET_ALL_PRIVACY_POLICY: 'Privacy Policy fetched successfully',
        CREATE_SUCCESS: 'Privacy Policy created successfully',
        PRIVACY_POLICY_SENT: 'Notification sent successfully',
        NOT_FOUND: 'Privacy Policy not found',
        GET_PRIVACY_POLICY: 'Privacy Policy Getting Successfully',
        UPDATE_FAILED: 'Privacy Policy update process failed',
        UPDATE_SUCCESS: 'Privacy Policy Update Successfully',
        DELETE_PRIVACY_POLICY: 'Privacy Policy Delete Successfully',
        NOT_SEND: 'Privacy Policy not Send',
        DEVICE_TOKEN_NOT_FOUND: 'Device Token not Found',
        USER_POLICY_ACCEPT: 'User Policy Accepted',
        USER_ALREADY_ACCEPTED: 'User Already Policy Accepted'
    },
    USER_ACHIEVEMENT_NOT_FOUND: 'User or Achievement not found',
    USER_NOTIFICATION_NOT_FOUND: 'User or Notification not found',
    USER_PREFERENCES_NOT_FOUND: 'User or Preference not found',
    USER_POLICY_NOT_FOUND: 'User of Policy not found',
    USER_SESSON_NOT_FOUND: 'User or Session not found',
    INVALID_TOKEN: 'JWT Token is Invalid',
    EMAIL_NOT_SENT: 'Email not sent, Try Again',
    INVALID_DATE_FORMAT: 'Date format is Invalid',
};

export const VALIDATION_PATTERNS = {
    EMAIL: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
    PASSWORD:
        /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{6,12}$/,
    FIRSTNAME: /^[a-zA-Z][A-Za-z]*$/,
    LASTNAME: /^[a-zA-Z][A-Za-z]*$/,
    NAME: /^([a-zA-Z][a-zA-Z]* ?)+$/,
};

export const VALIDATON_MESSAGES = {
    EMAIL: 'Please Enter a Email Valid',
    PASSWORD:
        'Password must have at least one uppercase letter, one lowercase letter, one special character, one digit, and be 8-12 characters long',
    FIRSTNAME: 'Please Enter a First Name Valid',
    LASTNAME: 'Please Enter a Last Name Valid',
    NAME: 'Please Enter a Name Valid',
    PASSWORD_INVALID: 'Password Invalid',
};

export const STATUS_CODES = {
    // 1XX INFORMATIONAL
    CONTINUE: 100,
    SWITCHING_PROTOCOLS: 101,
    PROCESSING: 102,
    EARLY_HINTS: 103,

    // 2XX SUCCESS
    SUCCESS: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NON_AUTHORITATIVE_INFORMATION: 203,
    NO_CONTENT: 204,
    RESET_CONTENT: 205,
    PARTIAL_CONTENT: 206,
    MULTI_STATUS: 207,
    ALREADY_REPORTED: 208,
    IM_USED: 226,

    // 3XX REDIRECTION
    MULTIPLE_CHOICES: 300,
    MOVED_PERMANENTLY: 301,
    FOUND: 302,
    SEE_OTHER: 303,
    NOT_MODIFIED: 304,
    USE_PROXY: 305,
    TEMPORARY_REDIRECT: 307,
    PERMANENT_REDIRECT: 308,

    // 4XX CLIENT ERROR
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    PAYMENT_REQUIRED: 402,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    NOT_ALLOWED: 405,
    NOT_ACCEPTABLE: 406,
    PROXY_AUTHENTICATION_REQUIRED: 407,
    REQUEST_TIMEOUT: 408,
    CONFLICT: 409,
    GONE: 410,
    LENGTH_REQUIRED: 411,
    PRECONDITION_FAILED: 412,
    PAYLOAD_TOO_LARGE: 413,
    URI_TOO_LONG: 414,
    UNSUPPORTED_MEDIA_TYPE: 415,
    RANGE_NOT_SATISFIABLE: 416,
    EXPECTATION_FAILED: 417,
    UNPROCESSABLE_ENTITY: 422,
    VALIDATION_ERROR: 422,
    NOT_VALID_DATA: 422,
    LOCKED: 423,
    FAILED_DEPENDENCY: 424,
    UNORDERED_COLLECTION: 425,
    UPGRADE_REQUIRED: 426,
    PRECONDITION_REQUIRED: 428,
    TOO_MANY_REQUESTS: 429,
    REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
    UNAVAILABLE_FOR_LEGAL_REASONS: 451,

    // 5XX SERVER ERROR
    SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504,
    HTTP_VERSION_NOT_SUPPORTED: 505,
    VARIANT_ALSO_NEGOTIATES: 506,
    INSUFFICIENT_STORAGE: 507,
    LOOP_DETECTED: 508,
    BANDWIDTH_LIMIT_EXCEEDED: 509,
    NOT_EXTENDED: 510,
    NETWORK_AUTHENTICATION_REQUIRED: 511,
};
